[package]
name = "micro-16"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.8.0"
byteorder = "1.5.0"
hound = "3.5.1"
pixels = "0.15.0"
prompted = "0.2.8"
tinyaudio = "2.0.0"
winit = "0.30.12"
